import React, { useEffect, useState } from 'react';
import { StyleSheet, View, TouchableOpacity, ActivityIndicator, Platform } from 'react-native';
import * as WebBrowser from 'expo-web-browser';
import * as Google from 'expo-auth-session/providers/google';

import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { Colors } from '@/constants/theme';
import { useColorScheme } from 'react-native';
import { useAuth } from '../_context';
import { supabase } from '@/lib/supabase';

WebBrowser.maybeCompleteAuthSession();

export default function LoginScreen() {
  const { signIn } = useAuth();
  const systemScheme = useColorScheme();
  const colorScheme = systemScheme === 'dark' ? 'dark' : 'light';
  const currentColors = Colors[colorScheme];

  const [loading, setLoading] = useState(false);

  const [request, response, promptAsync] = Google.useIdTokenAuthRequest({
    iosClientId: 'YOUR_IOS_CLIENT_ID.apps.googleusercontent.com',
    androidClientId: 'YOUR_ANDROID_CLIENT_ID.apps.googleusercontent.com',
    webClientId: '313656607388-jnus3vnvd2a8hmv05hno0gapffcso0hc.apps.googleusercontent.com',
  });

  // Handle Mobile Auth Session response
  useEffect(() => {
    async function handleAuthentication() {
      if (response?.type === 'success') {
        const idToken = response.params?.id_token || response.authentication?.idToken;
        setLoading(true);

        try {
          if (!idToken) {
            throw new Error('No Google ID token returned');
          }
          console.log("Token:", idToken);
          
          // Authenticate with Supabase passing the raw nonce generated by expo
          const { data: authData, error: supabaseAuthError } = await supabase.auth.signInWithIdToken({
            provider: 'google',
            token: idToken,
            nonce: request?.nonce,
          });
          
          if (supabaseAuthError) {
            console.error('Supabase Auth Error:', supabaseAuthError.message);
            setLoading(false);
            return;
          }

          const userEmail = authData.user?.email || '';
          console.log('Successfully logged in to Supabase as:', userEmail);

          let assignedRole: 'student' | 'teacher' = 'teacher';
          if (userEmail.toLowerCase().startsWith('st')) {
            assignedRole = 'student';
          }

          signIn(assignedRole, userEmail);
        } catch (error) {
          console.error('Failed to complete sign-in:', error);
        } finally {
          setLoading(false);
        }
      }
    }

    handleAuthentication();
  }, [response, request, signIn]);

  // Handle Web OAuth return redirect
  useEffect(() => {
    if (Platform.OS === 'web') {
      supabase.auth.getSession().then(({ data: { session } }) => {
        if (session?.user?.email) {
          const userEmail = session.user.email;
          let assignedRole: 'student' | 'teacher' = 'teacher';
          if (userEmail.toLowerCase().startsWith('st')) {
            assignedRole = 'student';
          }
          signIn(assignedRole, userEmail);
        }
      });
    }
  }, [signIn]);

  const handleLogin = async () => {
    if (Platform.OS === 'web') {
      // Direct Web OAuth prevents Cross-Origin-Opener-Policy window.closed issues
      setLoading(true);
      const { error } = await supabase.auth.signInWithOAuth({
        provider: 'google',
        options: {
          redirectTo: window.location.origin,
        },
      });
      if (error) {
        console.error('OAuth Redirect Error:', error.message);
        setLoading(false);
      }
    } else {
      await promptAsync();
    }
  };

  return (
    <ThemedView style={[styles.container, { backgroundColor: currentColors.background }]}>
      <View style={styles.centerContent}>
        <ThemedText style={styles.title}>Welcome to KARMA</ThemedText>
        <ThemedText style={[styles.subtitle, { color: currentColors.textSecondary }]}>
          Please sign in to access your portal
        </ThemedText>

        {loading ? (
          <ActivityIndicator size="large" color="#2563EB" style={{ marginVertical: 20 }} />
        ) : (
          <>
            {/* STUDENT BUTTON */}
            <TouchableOpacity
              disabled={Platform.OS !== 'web' && !request}
              style={[styles.loginButton, { backgroundColor: currentColors.text }]}
              onPress={handleLogin}
            >
              <ThemedText style={[styles.buttonText, { color: currentColors.background }]}>
                Sign in as Student
              </ThemedText>
            </TouchableOpacity>

            {/* TEACHER BUTTON */}
            <TouchableOpacity
              disabled={Platform.OS !== 'web' && !request}
              style={[styles.loginButton, styles.teacherButton, { borderColor: currentColors.text }]}
              onPress={handleLogin}
            >
              <ThemedText style={[styles.buttonText, { color: currentColors.text }]}>
                Sign in as Teacher
              </ThemedText>
            </TouchableOpacity>
          </>
        )}
      </View>
    </ThemedView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  centerContent: { width: '80%', alignItems: 'center', gap: 16 },
  title: { fontSize: 32, fontWeight: '800', marginBottom: 4 },
  subtitle: { fontSize: 16, textAlign: 'center', marginBottom: 24 },
  loginButton: {
    width: '100%',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  teacherButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    marginTop: 4,
  },
  buttonText: { fontSize: 16, fontWeight: '700' },
});